// Reflectors
//           ABCDEFGHIJKLMNOPQRSTUVWXYZ
char A[]  = "EJMZALYXVBWFCRQUONTSPIKHGD";
char Bw[] = "YRUHQSLDPXNGOKMIEBFZCWVJAT"; // Wide
char Cw[] = "FVPJIAOYEDRZXWGCTKUQSBNMHL"; // Wide
char Bt[] = "ENKQAUYWJICOPBLMDXZVFTHRGS"; // Thin
char Ct[] = "RDOBJNTKVEHMLFCWZAXGYIPSUQ"; // Thin

// Rotors
//             ABCDEFGHIJKLMNOPQRSTUVWXYZ
char I[]    = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"; // notches: R
char II[]   = "AJDKSIRUXBLHWTMCQGZNPYFVOE"; // notches: F
char III[]  = "BDFHJLCPRTXVZNYEIWGAKMUSQO"; // notches: W
char IV[]   = "ESOVPZJAYQUIRHXLNFTGKDCMWB"; // notches: K
char V[]    = "VZBRGITYUPSDNHLXAWMJQOFECK"; // notches: A
char VI[]   = "JPGVOUMFYQBENHZRDKASXLICTW"; // notches: AN
char VII[]  = "NZJHGRCXMYSWBOUFAIVLPEKQDT"; // notches: AN
char VIII[] = "FKQHTLXOCBJSPDZRAMEWNIUYGV"; // notches: AN


